CREATE TYPE "account_state" AS ENUM ('pending_verification', 'onboarding', 'active', 'limited', 'suspended', 'deletion_pending', 'banned', 'deleted');
CREATE TYPE "age_cohort" AS ENUM ('minor_16_17', 'adult_18_plus');
CREATE TYPE "visibility_audience" AS ENUM ('everyone', 'encounters', 'friends', 'only_me');
CREATE TYPE "policy_type" AS ENUM ('terms', 'community_guidelines');
CREATE TABLE "users" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "auth_subject" uuid NOT NULL, "account_state" account_state DEFAULT 'pending_verification' NOT NULL, "email_verified" boolean DEFAULT false NOT NULL, "birth_date_ciphertext" text, "birth_date_key_version" text, "age_cohort" age_cohort, "deleted_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "users_birth_date_encryption_complete" CHECK ((birth_date_ciphertext IS NULL AND birth_date_key_version IS NULL AND age_cohort IS NULL) OR (birth_date_ciphertext IS NOT NULL AND birth_date_key_version IS NOT NULL AND age_cohort IS NOT NULL)));
CREATE UNIQUE INDEX "users_auth_subject_active_uidx" ON "users" ("auth_subject") WHERE "deleted_at" IS NULL;
CREATE TABLE "profiles" ("user_id" uuid PRIMARY KEY REFERENCES "users"("id") ON DELETE CASCADE, "username" text NOT NULL, "normalized_username" text NOT NULL, "display_name" text NOT NULL, "avatar_object_key" text, "bio" text DEFAULT '' NOT NULL, "interests" jsonb DEFAULT '[]'::jsonb NOT NULL, "language" text, "region" text, "status" text DEFAULT '' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "profiles_username_length" CHECK (char_length(username) BETWEEN 3 AND 30), CONSTRAINT "profiles_normalized_username_format" CHECK (normalized_username ~ '^[a-z0-9_]{3,30}$'), CONSTRAINT "profiles_display_name_length" CHECK (char_length(display_name) BETWEEN 1 AND 80), CONSTRAINT "profiles_bio_length" CHECK (char_length(bio) <= 500));
CREATE UNIQUE INDEX "profiles_normalized_username_uidx" ON "profiles" ("normalized_username");
CREATE TABLE "profile_field_visibility" ("user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "field" text NOT NULL, "audience" visibility_audience NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, PRIMARY KEY ("user_id", "field"));
CREATE TABLE "user_settings" ("user_id" uuid PRIMARY KEY REFERENCES "users"("id") ON DELETE CASCADE, "reduced_motion" boolean DEFAULT false NOT NULL, "high_contrast" boolean DEFAULT false NOT NULL, "locale" text DEFAULT 'en' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "privacy_settings" ("user_id" uuid PRIMARY KEY REFERENCES "users"("id") ON DELETE CASCADE, "is_private" boolean DEFAULT false NOT NULL, "discoverable_by_username" boolean DEFAULT true NOT NULL, "allow_encounter_requests" boolean DEFAULT true NOT NULL, "show_presence" boolean DEFAULT true NOT NULL, "show_recent_activity" boolean DEFAULT false NOT NULL, "retain_encounter_history" boolean DEFAULT true NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "terms_acceptances" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT, "policy_type" policy_type NOT NULL, "policy_version" text NOT NULL, "source" text NOT NULL, "accepted_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "terms_acceptances_user_policy_version_uidx" ON "terms_acceptances" ("user_id", "policy_type", "policy_version");
CREATE TABLE "user_sessions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "user_id" uuid NOT NULL REFERENCES "users"("id") ON DELETE CASCADE, "device_label" text, "last_seen_at" timestamptz DEFAULT now() NOT NULL, "revoked_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "user_sessions_user_active_idx" ON "user_sessions" ("user_id") WHERE "revoked_at" IS NULL;
-- Browser roles receive no table grants. API/worker roles own business writes.
